name: PostmanPackage

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get latest version of postman
      run: curl --head -s "https://dl.pstmn.io/download/latest/linux64" | grep -o "Postman.*.gz"
    - name: Build the package
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: chmod u+x ./build-deb.sh && ./build-deb.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.PACKAGE_DIR }}
        path: ${{ env.PACKAGE_DIR }}
